---

- name: Container is running
  docker:
    image: elasticsearch
    name: elasticsearch
    ports:
      - "{{ es_port }}:9200"
    volumes:
      - "{{ data_dir }}/elasticsearch":/usr/share/elasticsearch/data
    restart_policy: always
  tags: [elasticsearch]
